In [ ]:
import pandas as pd
estoque = {
    "produto": ['caderno', 'caneta', 'mochila'],
    "categoria": ['papelaria', 'papelaria', 'acessorio'],
    "preco": [12.50, 2.30, 89.90],
}
# Panda sendo usado em um dicionario
display(pd.DataFrame(estoque))

   produto  categoria  preco
0  caderno  papelaria   12.5
1   caneta  papelaria    2.3
2  mochila  acessorio   89.9

Testando o pandas.... nunca abra o csv no excel........

In [ ]:
# df = pd.DataFrame(estoque) 
# df
# O delimitador default é a vírgula por tem que alterar o delimitador caso ele seja outro
df = pd.read_csv('vendas.csv', sep=';') # Estrutura de: nome_do_arquivo, separador/delimitador
df
# Resumindo o df basicamente carrega os dados do arquivo e depois usa essa variavel para fazer filtros e etc
# Dataframes não alteram CSV

              produto  quantidade_vendida  preco_unitario
0             caderno                  34            12.5
1              caneta                 120             2.3
2             mochila                   8            89.9
3              estojo                  22            15.0
4            borracha                  60             1.5
5               lapis                  95             1.2
6           apontador                  40             3.8
7               regua                  28             4.5
8   marcador de texto                  53             6.9
9         cola bastao                  37             5.2
10            tesoura                  19             7.4
11             agenda                  15            32.0
12           fichario                  12            24.9
13            grafite                  44             2.1
14          corretivo                  26             4.3

Coluna do faturamento

In [ ]:
# Se comporta igual a um dicionario
df['faturamento'] = df['quantidade_vendida'] * df['preco_unitario']
faturamento_total = df['faturamento'].sum()
faturamento_medio = df['faturamento'].mean()
# Se for display o pandas usa o numpy pra fazer o calculo ai aparece um np.float64 (numpy, tipo, binario)
print(f"Faturamento total: {faturamento_total} \nMédio: {faturamento_medio}")

3913.9
Faturamento total: 3913.9
Médio: 260.9266666666667

In [57]:
df.to_csv('vendas_python.csv', sep=';', index=False) # Estrutura parecida com o read_csv, primeiro vem o nome depois bem o separador e por ultimo o index.

Filtro

In [47]:
df_qnt_40 = df[df['quantidade_vendida'] >= 40] # Estrutura dataframe[filtro do dataframe/logica]
df_qnt_40

              produto  quantidade_vendida  preco_unitario  faturamento
1              caneta                 120             2.3        276.0
4            borracha                  60             1.5         90.0
5               lapis                  95             1.2        114.0
6           apontador                  40             3.8        152.0
8   marcador de texto                  53             6.9        365.7
13            grafite                  44             2.1         92.4